name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      SERVICE: api
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
      SERVER_USER_NAME: ${{ secrets.SERVER_USERNAME }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: pantyporowicz/osp-webapp-frontend:latest
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: cd osp/infra && git pull && make deploy
